[build]
  command = "echo 'no op'"
  publish = "public"

  [build.environment]
    YARN_FLAGS = "--frozen-lockfile"
    YARN_VERSION = "1.22.4"
    NODE_VERSION = "12"
    
[[plugins]]
package = "netlify-plugin-nimbella"

[nimbella]
functions = "functions"